name: 'RIOT! Concert Cinema'
favicon: null
layout_spectrum: 0.0932037418242544
typography_spectrum: 0.163918494945392
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.151819022372365
  lightness: 0.06420928286388516
  saturation: 0.33310735947452486
  rhythmicContrast: 0.742606493178755
purpose: []
